services:
  NS\TokenBundle\Generator\TokenGenerator:
    arguments: [ '%ns_token.id%', '%ns_token.signer%', '@ns_token.key', '%ns_token.issuer%', '%ns_token.audience%' ]
    shared: false
    public: false

  NS\TokenBundle\Twig\TokenGeneratorExtension:
    arguments: [ '@NS\TokenBundle\Generator\TokenGenerator', '%ns_token.short_expiration%', '%ns_token.long_expiration%' ]
    public: false
    tags:
      - { name: twig.extension }

  ns_token.generator:
    alias: NS\TokenBundle\Generator\TokenGenerator
    public: true

  ns_token.twig_extension:
    alias: NS\TokenBundle\Twig\TokenGeneratorExtension
    public: true

  ns_token.key:
    class: Lcobucci\JWT\Signer\Key
    arguments: ['%ns_token.key%']
